apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-piper
  name: hello-piper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-piper
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-piper
    spec:
      containers:
      - image: sameerarora11/hello-piper
        name: hello-piper
        resources: {}
status: {}
