apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: { { .Values.applicationName } }
  name: { { .Values.applicationName } }
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: { { .Values.applicationName } }
  type: { { .Values.service.type } }
status:
  loadBalancer: {}

